# Generated by Django 5.1.5 on 2025-02-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='user_type',
            field=models.CharField(choices=[('paciente', 'Paciente'), ('doctor', 'Doctor'), ('superuser', 'Superusuario')], default='paciente', max_length=10),
        ),
    ]
