# Generated by Django 4.2.16 on 2024-10-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('rh', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('estado_civil', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='doctors',
            name='identification_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='licence_number',
            field=models.BigIntegerField(),
        ),
    ]
