# Generated by Django 4.2.16 on 2024-10-31 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_paciente_doctors_identification_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paciente',
            new_name='Pacientes',
        ),
    ]
