# Generated by Django 5.1.1 on 2024-10-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='historia_medica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], default='masculino', max_length=10),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='vacunas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='frecuencia_cardiaca',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='frecuencia_respiratoria',
            field=models.IntegerField(default=0),
        ),
    ]
